#!/usr/bin/php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Database\Commands\SyncDatabaseCommand;
use Database\Commands\SyncTableCommand;
use Dotenv\Dotenv;

// Load env file.
$dotenv = new Dotenv(__DIR__);
$dotenv->load();

$app = new Application();
$app->add(new SyncDatabaseCommand);
$app->add(new SyncTableCommand);
$app->run();
