#!/usr/bin/php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use PhpMaster\Commands\FibonacciCommand;
use Database\Commands\SyncTableCommand;
use Dotenv\Dotenv;

// Load env file.
$dotenv = new Dotenv(__DIR__);
$dotenv->load();

$app = new Application();
$app->add(new FibonacciCommand);
$app->add(new SyncTableCommand);
$app->run();
